Plugins/ISDK.Filuet.Theme.FiluetHerbalife/Areas/Admin/Controllers/FiluetHerbalifeController.cs
using ISDK.Filuet.Theme.FiluetHerbalife.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System.Threading.Tasks;

namespace ISDK.Filuet.Theme.FiluetHerbalife.Areas.Admin.Controllers
{
    public class FiluetHerbalifeController : BasePluginController
    {
        #region Fields

        private readonly ThemeFiluetHerbalifeSettings _themeFiluetHerbalifeSettings;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;

        #endregion

        #region Ctor

        public FiluetHerbalifeController(
            ThemeFiluetHerbalifeSettings themeFiluetHerbalifeSettings,
            ILocalizationService localizationService,
            INotificationService notificationService,
            ISettingService settingService)
        {
            _themeFiluetHerbalifeSettings = themeFiluetHerbalifeSettings;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _settingService = settingService;
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public IActionResult Configure()
        {
            var model = new ConfigurationModel
            {
                CategoryIdForCatalogue = _themeFiluetHerbalifeSettings.CategoryIdForCatalogue,
                CategoryIdForProgramm = _themeFiluetHerbalifeSettings.CategoryIdForProgramm,
                OmnivaCarrierUrl = _themeFiluetHerbalifeSettings.OmnivaCarrierUrl,
                DPDLatviaCarrierUrl = _themeFiluetHerbalifeSettings.DPDLatviaCarrierUrl,
                DPDLithuaniaCarrierUrl = _themeFiluetHerbalifeSettings.DPDLithuaniaCarrierUrl,
                DPDEstoniaCarrierUrl = _themeFiluetHerbalifeSettings.DPDEstoniaCarrierUrl
            };
            return View(model);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!ModelState.IsValid)
                return Configure();

            _themeFiluetHerbalifeSettings.CategoryIdForCatalogue = model.CategoryIdForCatalogue;
            _themeFiluetHerbalifeSettings.CategoryIdForProgramm = model.CategoryIdForProgramm;
            _themeFiluetHerbalifeSettings.OmnivaCarrierUrl = model.OmnivaCarrierUrl;
            _themeFiluetHerbalifeSettings.DPDLatviaCarrierUrl = model.DPDLatviaCarrierUrl;
            _themeFiluetHerbalifeSettings.DPDLithuaniaCarrierUrl = model.DPDLithuaniaCarrierUrl;
            _themeFiluetHerbalifeSettings.DPDEstoniaCarrierUrl = model.DPDEstoniaCarrierUrl;
            await _settingService.SaveSettingAsync(_themeFiluetHerbalifeSettings);
            await _settingService.ClearCacheAsync();
            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));
            return Configure();
        }

        #endregion
    }
}

Plugins/ISDK.Filuet.Theme.FiluetHerbalife/Areas/Admin/Views/FiluetHerbalife/Configure.cshtml
@model ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
    var showTour = ViewBag.ShowTour ?? false;

    const string hideConfigure = "Configure";
    var customer = await workContext.GetCurrentCustomerAsync();
    var hideConfigureBlock = showTour ? false : await genericAttributeService.GetAttributeAsync<bool>(customer, hideConfigure);
}

<form asp-controller="FiluetHerbalife" asp-action="Configure" method="post">
    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <nop-cards id="product-cards">
                    <nop-card asp-name="product-info" asp-icon="fas fa-info" asp-title="@T("ISDK.Filuet.Theme.FiluetHerbalife.Configure")" asp-hide-block-attribute-name="@hideConfigure" asp-hide="@hideConfigureBlock" asp-advanced="false">
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="CategoryIdForCatalogue" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="CategoryIdForCatalogue" />
                                    <span asp-validation-for="CategoryIdForCatalogue"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="CategoryIdForProgramm" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="CategoryIdForProgramm" />
                                    <span asp-validation-for="CategoryIdForProgramm"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="OmnivaCarrierUrl" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="OmnivaCarrierUrl" />
                                    <span asp-validation-for="OmnivaCarrierUrl"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="DPDLatviaCarrierUrl" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="DPDLatviaCarrierUrl" />
                                    <span asp-validation-for="DPDLatviaCarrierUrl"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="DPDLithuaniaCarrierUrl" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="DPDLithuaniaCarrierUrl" />
                                    <span asp-validation-for="DPDLithuaniaCarrierUrl"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="DPDEstoniaCarrierUrl" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="DPDEstoniaCarrierUrl" />
                                    <span asp-validation-for="DPDEstoniaCarrierUrl"></span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-9 offset-md-3">
                                    <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                                </div>
                            </div>
                        </div>
                    </nop-card>
                </nop-cards>
            </div>
        </div>
    </section>
</form>